import { IBM_Plex_Sans, Space_Grotesk } from "next/font/google";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm_plex_sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const spaceGrotesk = Space_Grotesk({
  variable: "--font-space_grotesk",
  subsets: ["latin"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${ibmPlexSans.variable} scroll-smooth`}>
      <body className="bg-primary text-light leading-[1.55] bg-[linear-gradient(var(--line)_1px,transparent_1px),linear-gradient(90deg,var(--line)_1px,transparent_1px)] bg-size-[64px_64px] font-ibm-plex bg-fixed">
        {children}
      </body>
    </html>
  );
}
