import { IBM_Plex_Sans, Space_Grotesk } from "next/font/google";
import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "./components/Sidebar";
import SidebarMobile from "./components/SidebarMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm_plex_sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const spaceGrotesk = Space_Grotesk({
  variable: "--font-space_grotesk",
  subsets: ["latin"],
});

export default function AdminLayout({ children }: LayoutProps<"/admin">) {
  return (
    <html
      lang="en"
      className={`${ibmPlexSans.variable} ${spaceGrotesk.variable} scroll-smooth`}
    >
      <body className="flex items-start min-h-dvh font-ibm-plex text-light leading-[1.55] bg-primary">
        <Sidebar />

        <div className="sidebar-backdrop" id="sidebarBackdrop"></div>
        <div className="flex-1 min-w-0">
          <SidebarMobile />
          {children}
          <footer className="border-t border-solid border-line py-6.5 px-0">
            <div className="max-w-7xl mx-auto my-0 py-0 px-8 xl:max-w-360 xl:py-0 xl:px-10 flex justify-between items-center flex-wrap gap-3">
              <div
                className="flex items-center gap-2.5 font-space-grotesk font-bold text-[18px] shrink-0 no-underline"
                style={{ fontSize: "14px", textDecoration: "none" }}
              >
                <span
                  className="h-2.25 w-2.25 rounded-[50%] bg-accent shadow-[0_0_0_4px_rgba(255,182,39,0.14)] shrink-0"
                  style={{ width: "6px", height: "6px" }}
                ></span>
                PowerPulse Admin
              </div>
              <p className="text-faint text-[13px]">
                &copy; 2026 PowerPulse. Dummy data shown for preview only.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
